//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraineeCourse
    {
        public int CourseId { get; set; }
        public int TraineeId { get; set; }
        public System.DateTime RegisterationDate { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
